fixtures:
  repositories:
    apt: 'https://github.com/puppetlabs/puppetlabs-apt'   
    augeasproviders_core: "https://github.com/hercules-team/augeasproviders_core"
    augeasproviders_shellvar: "https://github.com/hercules-team/augeasproviders_shellvar"   
    debconf: 'https://github.com/smoeding/puppet-debconf'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
